const fs=require('fs');const sleep=m=>new Promise(r=>setTimeout(r,m));
(async()=>{const t=await(await fetch('http://127.0.0.1:9236/json')).json();const ws=new WebSocket(t.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let i=0;const p=new Map;ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const c=p.get(m.id);p.delete(m.id);m.error?c[1](m.error):c[0](m.result)}});const c=(method,params={})=>new Promise((a,b)=>{const id=++i;p.set(id,[a,b]);ws.send(JSON.stringify({id,method,params}))});const e=async expression=>(await c('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;const mouse=async selector=>{const b=await e(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});n.scrollIntoView({behavior:'instant',block:'center'});const r=n.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await sleep(300);await c('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...b});await c('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...b});await sleep(1000);};await c('Page.enable');await c('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});await c('Page.navigate',{url:'http://127.0.0.1:8123/leanix-bitas-2026-demo.html'});await sleep(1500);let r={};
await mouse('.hero .pill-btn');r.startDemo=await e(`document.querySelector('.step.active')?.dataset.t`);await mouse('.hero .pill-btn.ghost');r.downloadSummary=await e(`({section:document.querySelector('.step.active')?.dataset.t,url:location.href})`);
await mouse('.step[data-t="s3"]');r.mouseNav=await e(`document.querySelector('.step.active')?.dataset.t`);await mouse('#s3 .capture-card img');r.mouseLightbox=await e(`document.querySelector('.lightbox').classList.contains('open')`);await mouse('.lb-next');r.next=await e(`document.querySelector('.lb-count').innerText`);await mouse('.lb-prev');r.prev=await e(`document.querySelector('.lb-count').innerText`);await mouse('.lb-close');r.close=await e(`!document.querySelector('.lightbox').classList.contains('open')`);
await mouse('#s3 summary');r.mouseAccordion=await e(`document.querySelector('#s3 details').open`);await e(`document.querySelector('#s3 summary').click()`);await mouse('.prompt-chip:nth-child(3)');r.mousePrompt=await e(`document.querySelector('#promptResult').innerText`);await mouse('[data-panel="panelRest"]');r.mouseTab=await e(`!document.querySelector('#panelRest').hidden`);
r.footer=[];for(let j=1;j<=3;j++){await mouse(`.hub .features li:nth-child(${j}) a`);await sleep(1000);r.footer.push(await e(`({link:${j},y:scrollY,href:document.querySelector('.hub .features li:nth-child(${j}) a').getAttribute('href')})`));}
await mouse('.step[data-t="s3"]');await e(`document.querySelector('#s3 .capture-card img').click()`);await sleep(400);await c('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,x:5,y:500});await c('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,x:5,y:500});r.backdropClose=await e(`!document.querySelector('.lightbox').classList.contains('open')`);
r.reveals=[];await e(`document.querySelectorAll('details').forEach(d=>d.open=true)`);let height=await e('document.documentElement.scrollHeight');for(let y=0;y<height;y+=600){await e(`window.scrollTo({top:${y},behavior:'instant'})`);await sleep(150)}r.reveals=await e(`[...document.querySelectorAll('.reveal')].filter(n=>n.getClientRects().length&&!n.classList.contains('in')).map(n=>({tag:n.tagName,cls:n.className}))`);
await e(`window.scrollTo({top:0,behavior:'instant'})`);await sleep(200);r.tabStops=await e(`({images:[...document.querySelectorAll('.capture-card img')].map(n=>n.tabIndex),activeSectionAria:document.querySelector('.step.active')?.getAttribute('aria-current')})`);
fs.writeFileSync('C:/Users/ATDSOL/Working Directory/Personal Project/Bitas2026/audit/2026-09-13/interaction-audit.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));ws.close();})().catch(e=>{console.error(e);process.exitCode=1});