const fs=require('fs'),path=require('path');
const out='C:/Users/ATDSOL/Working Directory/Personal Project/Bitas2026/audit/2026-09-13';
const url='http://127.0.0.1:8123/leanix-bitas-2026-demo.html';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
const ts=await(await fetch('http://127.0.0.1:9236/json')).json();const ws=new WebSocket(ts.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let i=0;const p=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const c=p.get(m.id);p.delete(m.id);m.error?c[1](m.error):c[0](m.result);}});const call=(method,params={})=>new Promise((a,b)=>{const id=++i;p.set(id,[a,b]);ws.send(JSON.stringify({id,method,params}));});const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await call('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,mobile:false,deviceScaleFactor:1});
await call('Page.addScriptToEvaluateOnNewDocument',{source:`history.scrollRestoration='manual';window.scrollTo({top:0,behavior:'instant'});window.__perf={lcp:[],cls:[],long:[]};new PerformanceObserver(l=>window.__perf.lcp.push(...l.getEntries().map(e=>e.startTime))).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(l=>window.__perf.cls.push(...l.getEntries().filter(e=>!e.hadRecentInput).map(e=>e.value))).observe({type:'layout-shift',buffered:true});new PerformanceObserver(l=>window.__perf.long.push(...l.getEntries().map(e=>e.duration))).observe({type:'longtask',buffered:true});`});
const get=()=>ev(`({ready:document.readyState,nav:performance.getEntriesByType('navigation').map(e=>({load:e.loadEventEnd,dcl:e.domContentLoadedEventEnd})),paint:performance.getEntriesByType('paint').map(e=>({name:e.name,time:e.startTime})),observed:window.__perf,broken:[...document.querySelectorAll('.capture-card img')].filter(e=>e.naturalWidth===0).map(e=>e.src),loaded:document.querySelectorAll('.capture-card img').length,fonts:document.fonts.status,js:document.documentElement.classList.contains('js'),resourceBytes:performance.getEntriesByType('resource').reduce((s,e)=>s+e.transferSize,0)})`);
const r={local:[]};
for(let j=0;j<3;j++){await call('Network.clearBrowserCache');await call('Network.setCacheDisabled',{cacheDisabled:true});await call('Page.navigate',{url});await sleep(2500);r.local.push(await get());}
await call('Network.emulateNetworkConditions',{offline:false,latency:80,downloadThroughput:1250000,uploadThroughput:625000,connectionType:'wifi'});await call('Emulation.setCPUThrottlingRate',{rate:4});await call('Network.clearBrowserCache');await call('Page.navigate',{url});await sleep(16000);r.constrained={conditions:'10 Mbps down, 80 ms latency, 4x CPU throttling; local server/CDP simulation',result:await get()};
await call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await call('Emulation.setCPUThrottlingRate',{rate:1});
await call('Network.setBlockedURLs',{urls:['*://fonts.googleapis.com/*','*://fonts.gstatic.com/*']});await call('Network.clearBrowserCache');await call('Page.navigate',{url});await sleep(2500);r.fontsBlocked=await get();
await call('Page.navigate',{url:'file:///C:/Users/ATDSOL/Working%20Directory/Personal%20Project/Bitas2026/leanix-bitas-2026-demo.html'});await sleep(2500);r.fileWithFontsBlocked=await get();
await call('Network.setBlockedURLs',{urls:[]});await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await call('Page.navigate',{url});await sleep(2000);r.reducedMotion=await ev(`({animations:[...document.querySelectorAll('*')].filter(e=>getComputedStyle(e).animationName!=='none').length,scrollBehavior:getComputedStyle(document.documentElement).scrollBehavior,hiddenReveals:document.querySelectorAll('.reveal:not(.in)').length})`);
await call('Emulation.setEmulatedMedia',{features:[]});await call('Emulation.setDeviceMetricsOverride',{width:1366,height:768,mobile:false,deviceScaleFactor:1});await call('Page.navigate',{url});await sleep(2000);await ev(`document.querySelector('.step[data-t="s1"]').click()`);await sleep(1500);r.headerOcclusion=await ev(`(()=>{const h=document.querySelector('.stepper').getBoundingClientRect();const k=document.querySelector('#s1 .sec-head').getBoundingClientRect();return {headerBottom:h.bottom,sectionTop:document.querySelector('#s1').getBoundingClientRect().top,headingTop:k.top,headingBottom:k.bottom}})()`);
fs.writeFileSync(path.join(out,'performance-audit.json'),JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));ws.close();
})().catch(e=>{console.error(e);process.exitCode=1});
